CRITICAL - 2020-11-23 15:39:06 --> Invalid file: templates/dashboard.php
#0 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\View\View.php(228): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('templates/dashb...')
#1 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Common.php(1119): CodeIgniter\View\View->render('templates/dashb...', Array, true)
#2 C:\xampp\htdocs\ci4template\app\Controllers\Auth.php(22): view('templates/dashb...', Array)
#3 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Auth->index()
#4 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#5 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\ci4template\public\index.php(45): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#8 {main}
CRITICAL - 2020-11-23 15:49:00 --> Invalid file: auth/index.php
#0 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\View\View.php(228): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('auth/index.php')
#1 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Common.php(1119): CodeIgniter\View\View->render('auth/index', Array, true)
#2 C:\xampp\htdocs\ci4template\app\Controllers\Auth.php(22): view('auth/index', Array)
#3 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Auth->index()
#4 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#5 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\ci4template\public\index.php(45): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#8 {main}
CRITICAL - 2020-11-23 17:25:34 --> Unable to connect to the database.
#0 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Database\Database.php(109): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Database\Config.php(148): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\SQLite3\Connection))
#2 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Database\Migration.php(78): CodeIgniter\Database\Config::forge('tests')
#3 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(1026): CodeIgniter\Database\Migration->__construct()
#4 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(223): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#5 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Commands\Database\Migrate.php(128): CodeIgniter\Database\MigrationRunner->latest(NULL)
#6 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CLI\Commands.php(100): CodeIgniter\Commands\Database\Migrate->run(Array)
#7 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CLI\CommandRunner.php(107): CodeIgniter\CLI\Commands->run('migrate', Array)
#8 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CLI\CommandRunner.php(85): CodeIgniter\CLI\CommandRunner->index(Array)
#9 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(914): CodeIgniter\CLI\CommandRunner->_remap('index', 'migrate')
#10 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#11 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CLI\Console.php(86): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\ci4template\spark(57): CodeIgniter\CLI\Console->run()
#14 {main}
CRITICAL - 2020-11-23 18:20:33 --> Declaration of Myth\Auth\Filters\LoginFilter::before(CodeIgniter\HTTP\RequestInterface $request) must be compatible with CodeIgniter\Filters\FilterInterface::before(CodeIgniter\HTTP\RequestInterface $request, $arguments = NULL)
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2020-11-23 18:21:23 --> Declaration of Myth\Auth\Filters\LoginFilter::after(CodeIgniter\HTTP\RequestInterface $request, CodeIgniter\HTTP\ResponseInterface $response) must be compatible with CodeIgniter\Filters\FilterInterface::after(CodeIgniter\HTTP\RequestInterface $request, CodeIgniter\HTTP\ResponseInterface $response, $arguments = NULL)
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2020-11-23 18:24:13 --> Undefined variable: validation
#0 C:\xampp\htdocs\ci4template\app\Views\auth\login.php(25): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 25, Array)
#1 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\View\View.php(246): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Common.php(1119): CodeIgniter\View\View->render('\\App\\Views\\Auth...', Array, true)
#3 C:\xampp\htdocs\ci4template\vendor\myth\auth\src\Controllers\AuthController.php(54): view('\\App\\Views\\Auth...', Array)
#4 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(918): Myth\Auth\Controllers\AuthController->login()
#5 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#6 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\ci4template\public\index.php(45): CodeIgniter\CodeIgniter->run()
#8 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#9 {main}
CRITICAL - 2020-11-23 18:24:54 --> Undefined variable: validation
#0 C:\xampp\htdocs\ci4template\app\Views\auth\login.php(25): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 25, Array)
#1 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\View\View.php(246): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Common.php(1119): CodeIgniter\View\View->render('\\App\\Views\\Auth...', Array, true)
#3 C:\xampp\htdocs\ci4template\vendor\myth\auth\src\Controllers\AuthController.php(54): view('\\App\\Views\\Auth...', Array)
#4 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(918): Myth\Auth\Controllers\AuthController->login()
#5 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#6 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\ci4template\public\index.php(45): CodeIgniter\CodeIgniter->run()
#8 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#9 {main}
CRITICAL - 2020-11-23 18:25:25 --> Undefined variable: validation
#0 C:\xampp\htdocs\ci4template\app\Views\auth\login.php(27): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 27, Array)
#1 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\View\View.php(246): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Common.php(1119): CodeIgniter\View\View->render('\\App\\Views\\Auth...', Array, true)
#3 C:\xampp\htdocs\ci4template\vendor\myth\auth\src\Controllers\AuthController.php(54): view('\\App\\Views\\Auth...', Array)
#4 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(918): Myth\Auth\Controllers\AuthController->login()
#5 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#6 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\ci4template\public\index.php(45): CodeIgniter\CodeIgniter->run()
#8 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#9 {main}
CRITICAL - 2020-11-23 18:25:32 --> Undefined variable: title
#0 C:\xampp\htdocs\ci4template\app\Views\templates\auth.php(11): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 11, Array)
#1 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\View\View.php(246): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\View\View.php(257): CodeIgniter\View\View->render('templates/auth', Array, true)
#3 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Common.php(1119): CodeIgniter\View\View->render('\\App\\Views\\Auth...', Array, true)
#4 C:\xampp\htdocs\ci4template\vendor\myth\auth\src\Controllers\AuthController.php(54): view('\\App\\Views\\Auth...', Array)
#5 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(918): Myth\Auth\Controllers\AuthController->login()
#6 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#7 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\ci4template\public\index.php(45): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2020-11-23 18:26:54 --> Undefined variable: title
#0 C:\xampp\htdocs\ci4template\app\Views\templates\auth.php(11): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 11, Array)
#1 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\View\View.php(246): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\View\View.php(257): CodeIgniter\View\View->render('templates/auth', Array, true)
#3 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Common.php(1119): CodeIgniter\View\View->render('\\App\\Views\\Auth...', Array, true)
#4 C:\xampp\htdocs\ci4template\vendor\myth\auth\src\Controllers\AuthController.php(54): view('\\App\\Views\\Auth...', Array)
#5 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(918): Myth\Auth\Controllers\AuthController->login()
#6 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#7 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\ci4template\public\index.php(45): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2020-11-23 19:16:05 --> Call to undefined method App\Models\UserModel::withGroup
#0 C:\xampp\htdocs\ci4template\vendor\myth\auth\src\Controllers\AuthController.php(166): CodeIgniter\Model->__call('withGroup', Array)
#1 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(918): Myth\Auth\Controllers\AuthController->attemptRegister()
#2 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#3 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\ci4template\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2020-11-23 21:57:47 --> syntax error, unexpected ')'
#0 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Autoloader\Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->requireFile('C:\\xampp\\htdocs...')
#1 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Autoloader\Autoloader.php(258): CodeIgniter\Autoloader\Autoloader->loadInNamespace('Myth\\Auth\\Contr...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('Myth\\Auth\\Contr...')
#3 [internal function]: spl_autoload_call('Myth\\Auth\\Contr...')
#4 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(869): class_exists('\\Myth\\Auth\\Cont...', true)
#5 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(394): CodeIgniter\CodeIgniter->startController()
#6 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\ci4template\public\index.php(45): CodeIgniter\CodeIgniter->run()
#8 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#9 {main}
CRITICAL - 2020-11-23 22:38:38 --> You do not have sufficient permissions to access that page.
#0 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Filters\Filters.php(173): Myth\Auth\Filters\RoleFilter->before(Object(CodeIgniter\HTTP\IncomingRequest), Array)
#1 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(382): CodeIgniter\Filters\Filters->run('admin', 'before')
#2 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\ci4template\public\index.php(45): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#5 {main}
