CRITICAL - 2020-11-22 11:05:13 --> syntax error, unexpected '$data' (T_VARIABLE)
#0 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Router\Router.php(195): CodeIgniter\Router\Router->autoRoute('auth/register')
#1 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(793): CodeIgniter\Router\Router->handle('auth/register')
#2 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(364): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
#3 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\ci4template\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2020-11-22 11:05:13 --> syntax error, unexpected '$data' (T_VARIABLE)
#0 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Router\Router.php(195): CodeIgniter\Router\Router->autoRoute('auth/register')
#1 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(793): CodeIgniter\Router\Router->handle('auth/register')
#2 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(364): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
#3 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\ci4template\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2020-11-22 11:08:39 --> Undefined variable: userModel
#0 C:\xampp\htdocs\ci4template\app\Controllers\Auth.php(12): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 12, Array)
#1 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(890): App\Controllers\Auth->__construct()
#2 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->createController()
#3 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\ci4template\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2020-11-22 11:08:52 --> Undefined variable: userModel
#0 C:\xampp\htdocs\ci4template\app\Controllers\Auth.php(12): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 12, Array)
#1 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(890): App\Controllers\Auth->__construct()
#2 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->createController()
#3 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\ci4template\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2020-11-22 11:09:10 --> Undefined variable: userModel
#0 C:\xampp\htdocs\ci4template\app\Controllers\Auth.php(13): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 13, Array)
#1 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(890): App\Controllers\Auth->__construct()
#2 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->createController()
#3 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\ci4template\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2020-11-22 11:48:48 --> syntax error, unexpected 'session' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST)
#0 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Autoloader\Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->requireFile('C:\\xampp\\htdocs...')
#1 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Autoloader\Autoloader.php(258): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 C:\xampp\htdocs\ci4template\app\Controllers\Auth.php(7): spl_autoload_call('App\\Controllers...')
#4 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Router\Router.php(583): include_once('C:\\xampp\\htdocs...')
#5 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Router\Router.php(195): CodeIgniter\Router\Router->autoRoute('auth/index')
#6 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(793): CodeIgniter\Router\Router->handle('auth/index')
#7 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(364): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
#8 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\ci4template\public\index.php(45): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2020-11-22 11:52:16 --> Undefined variable: validation
#0 C:\xampp\htdocs\ci4template\app\Views\auth\login.php(25): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 25, Array)
#1 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\View\View.php(246): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Common.php(1119): CodeIgniter\View\View->render('auth/login', Array, true)
#3 C:\xampp\htdocs\ci4template\app\Controllers\Auth.php(27): view('auth/login', Array)
#4 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Auth->index()
#5 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#6 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\ci4template\public\index.php(45): CodeIgniter\CodeIgniter->run()
#8 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#9 {main}
CRITICAL - 2020-11-22 11:52:21 --> Undefined variable: validation
#0 C:\xampp\htdocs\ci4template\app\Views\auth\login.php(25): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 25, Array)
#1 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\View\View.php(246): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Common.php(1119): CodeIgniter\View\View->render('auth/login', Array, true)
#3 C:\xampp\htdocs\ci4template\app\Controllers\Auth.php(27): view('auth/login', Array)
#4 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Auth->index()
#5 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#6 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\ci4template\public\index.php(45): CodeIgniter\CodeIgniter->run()
#8 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#9 {main}
CRITICAL - 2020-11-22 11:52:24 --> Undefined variable: validation
#0 C:\xampp\htdocs\ci4template\app\Views\auth\login.php(25): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 25, Array)
#1 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\View\View.php(246): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Common.php(1119): CodeIgniter\View\View->render('auth/login', Array, true)
#3 C:\xampp\htdocs\ci4template\app\Controllers\Auth.php(27): view('auth/login', Array)
#4 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Auth->index()
#5 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#6 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\ci4template\public\index.php(45): CodeIgniter\CodeIgniter->run()
#8 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#9 {main}
CRITICAL - 2020-11-22 11:54:03 --> Undefined variable: validation
#0 C:\xampp\htdocs\ci4template\app\Views\auth\login.php(25): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 25, Array)
#1 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\View\View.php(246): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Common.php(1119): CodeIgniter\View\View->render('auth/login', Array, true)
#3 C:\xampp\htdocs\ci4template\app\Controllers\Auth.php(27): view('auth/login', Array)
#4 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Auth->index()
#5 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#6 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\ci4template\public\index.php(45): CodeIgniter\CodeIgniter->run()
#8 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#9 {main}
CRITICAL - 2020-11-22 12:00:22 --> Invalid file: auth/index.php
#0 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\View\View.php(228): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('auth/index.php')
#1 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Common.php(1119): CodeIgniter\View\View->render('auth/index', Array, true)
#2 C:\xampp\htdocs\ci4template\app\Controllers\Auth.php(35): view('auth/index', Array)
#3 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Auth->index()
#4 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#5 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\ci4template\public\index.php(45): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#8 {main}
CRITICAL - 2020-11-22 12:01:33 --> Invalid file: auth/index.php
#0 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\View\View.php(228): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('auth/index.php')
#1 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Common.php(1119): CodeIgniter\View\View->render('auth/index', Array, true)
#2 C:\xampp\htdocs\ci4template\app\Controllers\Auth.php(38): view('auth/index', Array)
#3 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Auth->index()
#4 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#5 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\ci4template\public\index.php(45): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#8 {main}
CRITICAL - 2020-11-22 12:01:54 --> Invalid file: auth/index.php
#0 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\View\View.php(228): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('auth/index.php')
#1 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Common.php(1119): CodeIgniter\View\View->render('auth/index', Array, true)
#2 C:\xampp\htdocs\ci4template\app\Controllers\Auth.php(40): view('auth/index', Array)
#3 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Auth->index()
#4 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#5 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\ci4template\public\index.php(45): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#8 {main}
CRITICAL - 2020-11-22 12:02:25 --> Invalid file: auth/index.php
#0 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\View\View.php(228): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('auth/index.php')
#1 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Common.php(1119): CodeIgniter\View\View->render('auth/index', Array, true)
#2 C:\xampp\htdocs\ci4template\app\Controllers\Auth.php(39): view('auth/index', Array)
#3 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Auth->index()
#4 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#5 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\ci4template\public\index.php(45): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#8 {main}
CRITICAL - 2020-11-22 12:02:27 --> Invalid file: auth/index.php
#0 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\View\View.php(228): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('auth/index.php')
#1 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Common.php(1119): CodeIgniter\View\View->render('auth/index', Array, true)
#2 C:\xampp\htdocs\ci4template\app\Controllers\Auth.php(39): view('auth/index', Array)
#3 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Auth->index()
#4 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#5 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\ci4template\public\index.php(45): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#8 {main}
CRITICAL - 2020-11-22 12:02:34 --> Invalid file: auth/index.php
#0 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\View\View.php(228): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('auth/index.php')
#1 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Common.php(1119): CodeIgniter\View\View->render('auth/index', Array, true)
#2 C:\xampp\htdocs\ci4template\app\Controllers\Auth.php(39): view('auth/index', Array)
#3 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Auth->index()
#4 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#5 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\ci4template\public\index.php(45): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#8 {main}
CRITICAL - 2020-11-22 12:02:36 --> Invalid file: auth/index.php
#0 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\View\View.php(228): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('auth/index.php')
#1 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Common.php(1119): CodeIgniter\View\View->render('auth/index', Array, true)
#2 C:\xampp\htdocs\ci4template\app\Controllers\Auth.php(39): view('auth/index', Array)
#3 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Auth->index()
#4 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#5 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\ci4template\public\index.php(45): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#8 {main}
CRITICAL - 2020-11-22 12:02:39 --> Invalid file: auth/index.php
#0 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\View\View.php(228): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('auth/index.php')
#1 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Common.php(1119): CodeIgniter\View\View->render('auth/index', Array, true)
#2 C:\xampp\htdocs\ci4template\app\Controllers\Auth.php(39): view('auth/index', Array)
#3 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Auth->index()
#4 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#5 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\ci4template\public\index.php(45): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#8 {main}
CRITICAL - 2020-11-22 12:02:48 --> Invalid file: auth/index.php
#0 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\View\View.php(228): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('auth/index.php')
#1 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Common.php(1119): CodeIgniter\View\View->render('auth/index', Array, true)
#2 C:\xampp\htdocs\ci4template\app\Controllers\Auth.php(40): view('auth/index', Array)
#3 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Auth->index()
#4 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#5 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\ci4template\public\index.php(45): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#8 {main}
CRITICAL - 2020-11-22 12:02:51 --> Invalid file: auth/index.php
#0 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\View\View.php(228): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('auth/index.php')
#1 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Common.php(1119): CodeIgniter\View\View->render('auth/index', Array, true)
#2 C:\xampp\htdocs\ci4template\app\Controllers\Auth.php(39): view('auth/index', Array)
#3 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Auth->index()
#4 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#5 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\ci4template\public\index.php(45): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#8 {main}
CRITICAL - 2020-11-22 12:02:55 --> Invalid file: /auth/index.php
#0 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\View\View.php(228): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('/auth/index.php')
#1 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Common.php(1119): CodeIgniter\View\View->render('/auth/index', Array, true)
#2 C:\xampp\htdocs\ci4template\app\Controllers\Auth.php(39): view('/auth/index', Array)
#3 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Auth->index()
#4 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#5 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\ci4template\public\index.php(45): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#8 {main}
CRITICAL - 2020-11-22 12:02:58 --> Invalid file: auth/index.php
#0 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\View\View.php(228): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('auth/index.php')
#1 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Common.php(1119): CodeIgniter\View\View->render('auth/index', Array, true)
#2 C:\xampp\htdocs\ci4template\app\Controllers\Auth.php(39): view('auth/index', Array)
#3 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Auth->index()
#4 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#5 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\ci4template\public\index.php(45): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#8 {main}
CRITICAL - 2020-11-22 12:03:41 --> Invalid file: auth/index.php
#0 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\View\View.php(228): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('auth/index.php')
#1 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Common.php(1119): CodeIgniter\View\View->render('auth/index', Array, true)
#2 C:\xampp\htdocs\ci4template\app\Controllers\Auth.php(39): view('auth/index', Array)
#3 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Auth->index()
#4 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#5 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\ci4template\public\index.php(45): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#8 {main}
CRITICAL - 2020-11-22 12:03:54 --> Invalid file: auth/index.php
#0 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\View\View.php(228): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('auth/index.php')
#1 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Common.php(1119): CodeIgniter\View\View->render('auth/index', Array, true)
#2 C:\xampp\htdocs\ci4template\app\Controllers\Auth.php(39): view('auth/index', Array)
#3 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Auth->index()
#4 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#5 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\ci4template\public\index.php(45): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#8 {main}
CRITICAL - 2020-11-22 12:03:56 --> Invalid file: auth/index.php
#0 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\View\View.php(228): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('auth/index.php')
#1 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Common.php(1119): CodeIgniter\View\View->render('auth/index', Array, true)
#2 C:\xampp\htdocs\ci4template\app\Controllers\Auth.php(39): view('auth/index', Array)
#3 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Auth->index()
#4 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#5 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\ci4template\public\index.php(45): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#8 {main}
CRITICAL - 2020-11-22 12:03:58 --> Invalid file: auth/index.php
#0 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\View\View.php(228): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('auth/index.php')
#1 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Common.php(1119): CodeIgniter\View\View->render('auth/index', Array, true)
#2 C:\xampp\htdocs\ci4template\app\Controllers\Auth.php(39): view('auth/index', Array)
#3 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Auth->index()
#4 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#5 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\ci4template\public\index.php(45): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#8 {main}
CRITICAL - 2020-11-22 12:04:03 --> Invalid file: auth/index.php
#0 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\View\View.php(228): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('auth/index.php')
#1 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Common.php(1119): CodeIgniter\View\View->render('auth/index', Array, true)
#2 C:\xampp\htdocs\ci4template\app\Controllers\Auth.php(39): view('auth/index', Array)
#3 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Auth->index()
#4 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#5 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\ci4template\public\index.php(45): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#8 {main}
CRITICAL - 2020-11-22 12:04:13 --> Invalid file: auth/index.php
#0 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\View\View.php(228): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('auth/index.php')
#1 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Common.php(1119): CodeIgniter\View\View->render('auth/index', Array, true)
#2 C:\xampp\htdocs\ci4template\app\Controllers\Auth.php(39): view('auth/index', Array)
#3 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Auth->index()
#4 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#5 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\ci4template\public\index.php(45): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#8 {main}
CRITICAL - 2020-11-22 12:07:13 --> Undefined variable: validation
#0 C:\xampp\htdocs\ci4template\app\Controllers\Auth.php(20): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 20, Array)
#1 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Auth->index()
#2 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#3 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\ci4template\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2020-11-22 12:08:07 --> Undefined variable: validation
#0 C:\xampp\htdocs\ci4template\app\Controllers\Auth.php(20): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 20, Array)
#1 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(918): App\Controllers\Auth->index()
#2 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#3 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\ci4template\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2020-11-22 13:13:34 --> Unable to connect to the database.
#0 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Database\Database.php(109): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Database\Config.php(148): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\SQLite3\Connection))
#2 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Database\Migration.php(78): CodeIgniter\Database\Config::forge('tests')
#3 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(1026): CodeIgniter\Database\Migration->__construct()
#4 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(223): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#5 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Commands\Database\Migrate.php(128): CodeIgniter\Database\MigrationRunner->latest(NULL)
#6 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CLI\Commands.php(100): CodeIgniter\Commands\Database\Migrate->run(Array)
#7 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CLI\CommandRunner.php(107): CodeIgniter\CLI\Commands->run('migrate', Array)
#8 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CLI\CommandRunner.php(85): CodeIgniter\CLI\CommandRunner->index(Array)
#9 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(914): CodeIgniter\CLI\CommandRunner->_remap('index', 'migrate')
#10 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#11 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CLI\Console.php(86): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\ci4template\spark(57): CodeIgniter\CLI\Console->run()
#14 {main}
CRITICAL - 2020-11-22 13:14:10 --> Unable to connect to the database.
#0 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Database\Database.php(109): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Database\Config.php(148): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\SQLite3\Connection))
#2 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Database\Migration.php(78): CodeIgniter\Database\Config::forge('tests')
#3 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(1026): CodeIgniter\Database\Migration->__construct()
#4 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(223): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#5 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Commands\Database\Migrate.php(128): CodeIgniter\Database\MigrationRunner->latest(NULL)
#6 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CLI\Commands.php(100): CodeIgniter\Commands\Database\Migrate->run(Array)
#7 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CLI\CommandRunner.php(107): CodeIgniter\CLI\Commands->run('migrate', Array)
#8 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CLI\CommandRunner.php(85): CodeIgniter\CLI\CommandRunner->index(Array)
#9 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(914): CodeIgniter\CLI\CommandRunner->_remap('index', 'migrate')
#10 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#11 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CLI\Console.php(86): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\ci4template\spark(57): CodeIgniter\CLI\Console->run()
#14 {main}
CRITICAL - 2020-11-22 13:15:28 --> Unable to connect to the database.
#0 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Database\Database.php(109): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Database\Config.php(148): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\SQLite3\Connection))
#2 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Database\Migration.php(78): CodeIgniter\Database\Config::forge('tests')
#3 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(1026): CodeIgniter\Database\Migration->__construct()
#4 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(223): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#5 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Commands\Database\Migrate.php(128): CodeIgniter\Database\MigrationRunner->latest(NULL)
#6 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CLI\Commands.php(100): CodeIgniter\Commands\Database\Migrate->run(Array)
#7 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CLI\CommandRunner.php(107): CodeIgniter\CLI\Commands->run('migrate', Array)
#8 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CLI\CommandRunner.php(85): CodeIgniter\CLI\CommandRunner->index(Array)
#9 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(914): CodeIgniter\CLI\CommandRunner->_remap('index', 'migrate')
#10 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#11 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CLI\Console.php(86): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\ci4template\spark(57): CodeIgniter\CLI\Console->run()
#14 {main}
CRITICAL - 2020-11-22 13:15:54 --> Unable to connect to the database.
#0 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Database\Database.php(109): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Database\Config.php(148): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\SQLite3\Connection))
#2 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Database\Migration.php(78): CodeIgniter\Database\Config::forge('tests')
#3 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(1026): CodeIgniter\Database\Migration->__construct()
#4 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(223): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#5 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Commands\Database\Migrate.php(128): CodeIgniter\Database\MigrationRunner->latest(NULL)
#6 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CLI\Commands.php(100): CodeIgniter\Commands\Database\Migrate->run(Array)
#7 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CLI\CommandRunner.php(107): CodeIgniter\CLI\Commands->run('migrate', Array)
#8 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CLI\CommandRunner.php(85): CodeIgniter\CLI\CommandRunner->index(Array)
#9 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(914): CodeIgniter\CLI\CommandRunner->_remap('index', 'migrate')
#10 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#11 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CLI\Console.php(86): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\ci4template\spark(57): CodeIgniter\CLI\Console->run()
#14 {main}
CRITICAL - 2020-11-22 13:17:23 --> Unable to connect to the database.
#0 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Database\Database.php(109): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Database\Config.php(148): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\SQLite3\Connection))
#2 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Database\Migration.php(78): CodeIgniter\Database\Config::forge('tests')
#3 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(1026): CodeIgniter\Database\Migration->__construct()
#4 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(223): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#5 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Commands\Database\Migrate.php(128): CodeIgniter\Database\MigrationRunner->latest(NULL)
#6 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CLI\Commands.php(100): CodeIgniter\Commands\Database\Migrate->run(Array)
#7 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CLI\CommandRunner.php(107): CodeIgniter\CLI\Commands->run('migrate', Array)
#8 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CLI\CommandRunner.php(85): CodeIgniter\CLI\CommandRunner->index(Array)
#9 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(914): CodeIgniter\CLI\CommandRunner->_remap('index', 'migrate')
#10 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#11 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CLI\Console.php(86): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\ci4template\spark(57): CodeIgniter\CLI\Console->run()
#14 {main}
CRITICAL - 2020-11-22 13:17:53 --> Unable to connect to the database.
#0 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Database\Database.php(109): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Database\Config.php(148): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\SQLite3\Connection))
#2 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Database\Migration.php(78): CodeIgniter\Database\Config::forge('tests')
#3 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(1026): CodeIgniter\Database\Migration->__construct()
#4 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(223): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#5 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Commands\Database\Migrate.php(128): CodeIgniter\Database\MigrationRunner->latest(NULL)
#6 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CLI\Commands.php(100): CodeIgniter\Commands\Database\Migrate->run(Array)
#7 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CLI\CommandRunner.php(107): CodeIgniter\CLI\Commands->run('migrate', Array)
#8 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CLI\CommandRunner.php(85): CodeIgniter\CLI\CommandRunner->index(Array)
#9 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(914): CodeIgniter\CLI\CommandRunner->_remap('index', 'migrate')
#10 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#11 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CLI\Console.php(86): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\ci4template\spark(57): CodeIgniter\CLI\Console->run()
#14 {main}
CRITICAL - 2020-11-22 13:19:54 --> Unable to connect to the database.
#0 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Database\Database.php(109): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Database\Config.php(148): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\SQLite3\Connection))
#2 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Database\Migration.php(78): CodeIgniter\Database\Config::forge('tests')
#3 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(1026): CodeIgniter\Database\Migration->__construct()
#4 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(223): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#5 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Commands\Database\Migrate.php(128): CodeIgniter\Database\MigrationRunner->latest(NULL)
#6 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CLI\Commands.php(100): CodeIgniter\Commands\Database\Migrate->run(Array)
#7 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CLI\CommandRunner.php(107): CodeIgniter\CLI\Commands->run('migrate', Array)
#8 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CLI\CommandRunner.php(85): CodeIgniter\CLI\CommandRunner->index(Array)
#9 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(914): CodeIgniter\CLI\CommandRunner->_remap('index', 'migrate')
#10 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#11 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CLI\Console.php(86): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\ci4template\spark(57): CodeIgniter\CLI\Console->run()
#14 {main}
CRITICAL - 2020-11-22 13:20:07 --> Unable to connect to the database.
#0 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Database\Database.php(109): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Database\Config.php(148): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\SQLite3\Connection))
#2 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Database\Migration.php(78): CodeIgniter\Database\Config::forge('tests')
#3 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(1026): CodeIgniter\Database\Migration->__construct()
#4 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(223): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#5 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Commands\Database\Migrate.php(128): CodeIgniter\Database\MigrationRunner->latest(NULL)
#6 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CLI\Commands.php(100): CodeIgniter\Commands\Database\Migrate->run(Array)
#7 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CLI\CommandRunner.php(107): CodeIgniter\CLI\Commands->run('migrate', Array)
#8 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CLI\CommandRunner.php(85): CodeIgniter\CLI\CommandRunner->index(Array)
#9 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(914): CodeIgniter\CLI\CommandRunner->_remap('index', 'migrate')
#10 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#11 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CLI\Console.php(86): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\ci4template\spark(57): CodeIgniter\CLI\Console->run()
#14 {main}
CRITICAL - 2020-11-22 13:27:05 --> Declaration of Myth\Auth\Filters\LoginFilter::before(CodeIgniter\HTTP\RequestInterface $request) must be compatible with CodeIgniter\Filters\FilterInterface::before(CodeIgniter\HTTP\RequestInterface $request, $arguments = NULL)
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2020-11-22 13:28:24 --> Declaration of Myth\Auth\Filters\LoginFilter::after(CodeIgniter\HTTP\RequestInterface $request, CodeIgniter\HTTP\ResponseInterface $response) must be compatible with CodeIgniter\Filters\FilterInterface::after(CodeIgniter\HTTP\RequestInterface $request, CodeIgniter\HTTP\ResponseInterface $response, $arguments = NULL)
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2020-11-22 13:28:29 --> Declaration of Myth\Auth\Filters\LoginFilter::after(CodeIgniter\HTTP\RequestInterface $request, CodeIgniter\HTTP\ResponseInterface $response) must be compatible with CodeIgniter\Filters\FilterInterface::after(CodeIgniter\HTTP\RequestInterface $request, CodeIgniter\HTTP\ResponseInterface $response, $arguments = NULL)
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2020-11-22 13:59:02 --> Class 'Myth\Auth\Filters\LoginFilter' not found
#0 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(382): CodeIgniter\Filters\Filters->run('login', 'before')
#1 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#2 C:\xampp\htdocs\ci4template\public\index.php(45): CodeIgniter\CodeIgniter->run()
#3 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#4 {main}
CRITICAL - 2020-11-22 13:59:02 --> Class 'Myth\Auth\Filters\LoginFilter' not found
#0 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(382): CodeIgniter\Filters\Filters->run('login', 'before')
#1 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#2 C:\xampp\htdocs\ci4template\public\index.php(45): CodeIgniter\CodeIgniter->run()
#3 C:\xampp\htdocs\ci4template\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#4 {main}
